spring:
  application:
    name: SERVER

  datasource:
    url: jdbc:postgresql://localhost:5432/xscord
    username: hamza
    password: hamza

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Africa/Casablanca



application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.recyclehub.backend: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
